CustomerSupport/Models/CreateTicketViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CustomerSupport.Models
{
    public class CreateTicketViewModel : IValidatableObject
    {
        [Required]
        [Display(Name = "Description")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Display(Name = "Due Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime DueDate { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (DueDate < DateTime.Now)
            {
                yield return new ValidationResult("Due date cannot be in the past.", new[] { "DueDate" });
            }
        }
    }
}

CustomerSupport/Models/EditTicketViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CustomerSupport.Models
{
    public class EditTicketViewModel
    {
        public Guid Id { get; set; }

        [Required]
        [Display(Name = "Description")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Display(Name = "Due Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime DueDate { get; set; }
    }
}

CustomerSupport/Models/ITicketViewModelToDomainModelMapper.cs
using BusinessLogic;

namespace CustomerSupport.Models
{
    public interface ITicketViewModelToDomainModelMapper
    {
        Ticket MapCreateViewModel(CreateTicketViewModel viewModel);
        Ticket MapEditViewModel(EditTicketViewModel viewModel);
    }
}

CustomerSupport/Models/IViewModelProvider.cs
using BusinessLogic;

namespace CustomerSupport.Models
{
    public interface IViewModelProvider
    {
        CreateTicketViewModel ProvideCreateTicketViewModel(Ticket ticket);
        EditTicketViewModel ProvideEditTicketViewModel(Ticket ticket);
        ListTicketViewModel ProvideListTicketViewModel(Ticket ticket);
    }
}

CustomerSupport/Models/ListTicketViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using BusinessLogic;

namespace CustomerSupport.Models
{
    public class ListTicketViewModel
    {
        public Guid Id { get; set; }

        public bool Urgent => (DueDate - DateTime.Now).TotalMinutes < 60;

        [Display(Name = "Description")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Display(Name = "Due Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime DueDate { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Time of submission")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime CreationDateTime { get; set; }
    }
}

CustomerSupport/Models/TicketViewModelProvider.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BusinessLogic;

namespace CustomerSupport.Models
{
    public class TicketViewModelProvider : IViewModelProvider
    {
        public CreateTicketViewModel ProvideCreateTicketViewModel(Ticket ticket)
        {
            var viewModel = new CreateTicketViewModel
            {
                Description = ticket.Description,
                DueDate = ticket.DueDate
            };

            return viewModel;
        }

        public EditTicketViewModel ProvideEditTicketViewModel(Ticket ticket)
        {
            var viewModel = new EditTicketViewModel
            {
                Description = ticket.Description,
                DueDate = ticket.DueDate,
                Id = ticket.Id
            };

            return viewModel;
        }

        public ListTicketViewModel ProvideListTicketViewModel(Ticket ticket)
        {
            var viewModel = new ListTicketViewModel
            {
                CreationDateTime = ticket.CreationDateTime,
                Description = ticket.Description,
                DueDate = ticket.DueDate,
                Id = ticket.Id
            };

            return viewModel;
        }
    }
}

CustomerSupport/Models/TicketViewModelToDomainModelMapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BusinessLogic;

namespace CustomerSupport.Models
{
    public class TicketViewModelToDomainModelMapper : ITicketViewModelToDomainModelMapper
    {
        private readonly IRepository _repository;

        public TicketViewModelToDomainModelMapper(IRepository repository)
        {
            _repository = repository;
        }

        public Ticket MapCreateViewModel(CreateTicketViewModel viewModel)
        {
            var ticket = new Ticket
            {
                Description = viewModel.Description,
                DueDate = viewModel.DueDate
            };

            return ticket;
        }

        public Ticket MapEditViewModel(EditTicketViewModel viewModel)
        {
            var ticket = _repository.GetTicket(viewModel.Id);

            ticket.Description = viewModel.Description;
            ticket.DueDate = viewModel.DueDate;

            return ticket;
        }
    }
}

CustomerSupport/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;
using BusinessLogic;
using CustomerSupport.Models;

namespace CustomerSupport.Controllers
{

    public class TicketController : Controller
    {
        private readonly IRepository _repository;
        private readonly IViewModelProvider _viewModelProvider;
        private readonly ITicketViewModelToDomainModelMapper _mapper;

        public TicketController(IRepository repository, IViewModelProvider viewModelProvider, ITicketViewModelToDomainModelMapper mapper)
        {
            _repository = repository;
            _viewModelProvider = viewModelProvider;
            _mapper = mapper;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateTicketViewModel ticketViewModel)
        {
            if (!ModelState.IsValid) return View("Index");

            var ticket = _mapper.MapCreateViewModel(ticketViewModel);

            _repository.AddTicket(ticket);
            return RedirectToAction("List");
        }

        public ActionResult Edit(Guid? id)
        {
            if (!id.HasValue) return View("Index");

            var ticket = _repository.GetTicket(id.Value);
            var ticketViewModel = _viewModelProvider.ProvideEditTicketViewModel(ticket);

            return View(ticketViewModel);
        }

        [HttpPost]
        public ActionResult Edit(EditTicketViewModel ticketViewModel)
        {
            if (!ModelState.IsValid) return View("Edit");

            var ticket = _mapper.MapEditViewModel(ticketViewModel);

            _repository.UpdateTicket(ticket);

            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            var tickets = _repository.GetAllTickets();
            var ticketViewModels = new List<ListTicketViewModel>();

            foreach (var ticket in tickets)
            {
                var ticketViewModel = _viewModelProvider.ProvideListTicketViewModel(ticket);
                ticketViewModels.Add(ticketViewModel);
            }

            return View(ticketViewModels);
        }

        [HttpPost]
        public ActionResult Delete(Guid? id)
        {
            if (!id.HasValue) return View("Index");

            _repository.DeleteTicket(id.Value);

            return RedirectToAction("List");
        }
    }
}

CustomerSupport/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/moment")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Submit a ticket", "Index", "Ticket", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Active tickets", "List", "Ticket")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CustomerSupport/Views/Ticket/Edit.cshtml
@model CustomerSupport.Models.EditTicketViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Ticket", FormMethod.Post))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DueDate, new { @class = "form-control datetimepicker " })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section scripts {
    @Scripts.Render("~/bundles/moment")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript">
        $(function () {
            $('.datetimepicker').datetimepicker({
                minDate: moment().add(5, 'minutes'),
                format: "YYYY/MM/DD HH:mm"
            });
            $('.datetimepicker').val("@Model.DueDate.ToString("yyyy'/'MM'/'dd HH:mm")");
        });
    </script>
}

CustomerSupport/Views/Ticket/Index.cshtml
@model CustomerSupport.Models.CreateTicketViewModel

@using (Html.BeginForm("Create", "Ticket", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br />
        <h4>Please submit a ticket for customer support</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Please describe the problem", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DueDate, new { @class = "form-control datetimepicker " })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section scripts {
    @Scripts.Render("~/bundles/moment")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")

    <script type="text/javascript">
        $(function () {
            $('.datetimepicker').datetimepicker({
                minDate: moment().add('minutes', 5),
                format: "YYYY/MM/DD HH:mm"
            });
        });
    </script>
}

CustomerSupport/Views/Ticket/List.cshtml
@model IEnumerable<CustomerSupport.Models.ListTicketViewModel>
<br />
<h4>All active tickets</h4>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DueDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreationDateTime)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr style="@(item.Urgent ? "Background-color:rgba(255,0,0,0.5)" : "")">
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDateTime)
            </td>
            <td>
                
                <button onclick="location.href = '@Url.Action("Edit", "Ticket", new {id = item.Id})';return false;"style = "float:left;"> Edit </button> 
                @using (Html.BeginForm("Delete", "Ticket", new {id = item.Id}))
                {
                    <button style = "float:left;">Delete</button>
                }
            </td>
        </tr>
    }
</table>